pagbank:
  token: 19612E2F787E4E0E8A32ED6E4F3BDDA8  # Set your PagBank sandbox API token here before running
  environment: SANDBOX
  log-requests: true

spring:
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    io.github.rodrigoma.pagbank: DEBUG
